apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-4learning
  labels:
    app: PVC-4learning
spec:
  #The storageClassName field specifies the name of the StorageClass and it should match the storageClassName of the PersistentVolume that you want to bind to this PersistentVolumeClaim. In this case, it is set to local-storage-4learning, which means that the PersistentVolumeClaim will be bound to the PersistentVolume with the same storageClassName.
  storageClassName: local-storage-4learning
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #The volumeMode should match the volumeMode of the PersistentVolume that you want to bind to this PersistentVolumeClaim. In this case, it is set to Filesystem, which means that the PersistentVolumeClaim will be bound to the PersistentVolume with the same volumeMode.
  volumeMode: Filesystem