apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-4learning
spec:
  selector:
    matchLabels:
      app: busybox 
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.1
        command: 
          - sh 
          - -c 
          - 'sleep 3600'
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        # The name of the volumeMounts must match the name of the volumeClaimTemplates
        - name: local-volume-4learning-with-statefulset
          #The mountPath must match the path specified in the PVs
          #But in the case of StatefulSets, the mountPath can be different for each replica, as the volumeClaimTemplates will create a unique PVC for each replica.
          #The mountPath can be different for each replica, as the volumeClaimTemplates will create a unique PVC for each replica, and the mountPath can be different for each PVC.
          mountPath: /mnt/disks/vol1/
  # The volumeClaimTemplates will create a unique PVC for each replica, and the mountPath can be different for each PVC.
  volumeClaimTemplates:
  - metadata:
      name: local-volume-4learning-with-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #The StorageClassName must match the name of the StorageClass created for the PVs
      storageClassName: local-storage-4learning
      resources:
        requests:
          storage: 1Gi